# Generated by Django 5.1.2 on 2024-11-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('id_manga', models.CharField(max_length=100)),
                ('id_emp', models.CharField(max_length=25)),
                ('id_cliente', models.CharField(max_length=25)),
                ('cantidad', models.IntegerField()),
                ('total', models.PositiveIntegerField()),
                ('fecha_venta', models.DateField()),
            ],
        ),
    ]
