# Generated by Django 5.1.2 on 2024-11-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=35)),
                ('prod_adqu', models.CharField(max_length=100)),
                ('tipo_pago', models.CharField(max_length=20)),
                ('num_tel', models.IntegerField()),
                ('total_compra', models.IntegerField()),
            ],
        ),
    ]
