# Generated by Django 5.1.2 on 2024-11-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id_manga', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('volumen', models.IntegerField()),
                ('genero', models.CharField(max_length=25)),
                ('sinopsis', models.CharField(max_length=100)),
                ('fecha_publ', models.DateField()),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
