# Generated by Django 5.1.2 on 2024-11-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_emp', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=100)),
                ('area_gen', models.CharField(max_length=25)),
                ('sueldo', models.PositiveIntegerField()),
            ],
        ),
    ]
