# Generated by Django 5.1 on 2024-11-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados_app', '0002_alter_empleado_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.IntegerField(max_length=10),
        ),
    ]
