# Generated by Django 5.1.2 on 2024-11-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('id_edit', models.CharField(max_length=25)),
                ('id_manga', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=20)),
                ('foto', models.ImageField(upload_to='')),
                ('estado', models.CharField(max_length=35)),
                ('nacionalidad', models.CharField(max_length=35)),
                ('num_tel', models.IntegerField()),
                ('correo', models.CharField(max_length=35)),
                ('ciudad', models.CharField(max_length=35)),
            ],
        ),
    ]
